layout_spectrum: 0.277403
color:
  saturation: 0.5969646
  lightness: 0.8136594
  brandStrength: 0.5320405
  brandColors:
    - '#020426'
    - '#396491'
    - '#FFFAE9'
    - '#D8B49A'
    - '#02D8F3'
  rhythmicContrast: 0.4021922
typography_spectrum: 1
name: Rahul Rekapalli Photography
